/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/fpga/hellogd/al_ip/ck.v
 ** Date	:	2019 09 26
 ** TD version	:	4.5.12562
\************************************************************/

`timescale 1ns / 1ps

module test ( i, o );
output 		o;
input  		i;

		EG_LOGIC_BUFG bufg(
		.i(i),
		.o(o));

endmodule