-d C:/fpga/Tang-Nano-examples/nano/impl/synthesize/rev_1/nano.vm
-p GW1N-1-QFN48-5
-pn GW1N-LV1QN48C5/I4
-cst C:\fpga\Tang-Nano-examples\nano\src\nano.cst
-cfg C:\fpga\Tang-Nano-examples\nano\impl\pnr\device.cfg
-sdc C:\fpga\Tang-Nano-examples\nano\src\nano.sdc
-bit
-tr
-ph
-timing
